sudo: false
language: node_js
node_js:
  - "6"
cache: yarn
before_script:
  - cd $TRAVIS_BUILD_DIR/packages/neoform/; yarn
  - cd $TRAVIS_BUILD_DIR/packages/neoform-validation/; yarn
  - cd $TRAVIS_BUILD_DIR
script: yarn start ci
